### ISSUE TITLE
ceph rbd client macos

### ISSUE THREAD

**Issue by f1-outsourcing** [zjx20/minikube-ceph-macOS-M1#1]
Hi, I hope you do not mind me writing you here. I was looking for some 'easy' solution to get a ceph client (rbd kernel mount?) for macos. I only see manuals of compiling ceph for mac. Do you know if I am missing something, is nobody offering such binaries?

**Comment by zjx20** [comment]
I found https://github.com/mulbc/homebrew-ceph-client or https://github.com/ailabstw/homebrew-ceph-fuse from the search engine; maybe you can try them. I hope this can help, but please note that I am not a ceph expert and I don't actually know how to use a ceph client.

**Comment by f1-outsourcing** [comment]
Thanks! I will give them a try. It looks like there is even a binary.
